<template>
    <div class="spa-conetnt">
        <div class="main-width">
            <h1>DISCLAIMERS</h1>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF THE CAYMAN ISLANDS: THIS DOES NOT CONSTITUTE THE OFFER OR SALE OF SECURITIES, WHETHER BY WAY OF SALE OR SUBSCRIPTION, IN THE CAYMAN ISLANDS.</p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF CHINA: THE RIGHTS ARE NOT BEING OFFERED OR SOLD AND MAY NOT BE OFFERED OR SOLD, DIRECTLY OR INDIRECTLY, WITHIN THE PEOPLE’S REPUBLIC OF CHINA (FOR SUCH PURPOSES, NOT INCLUDING THE HONG KONG AND MACAU SPECIAL ADMINISTRATIVE REGIONS OR TAIWAN), EXCEPT AS PERMITTED BY THE SECURITIES AND OTHER LAWS AND REGULATIONS OF THE PEOPLE’S REPUBLIC OF CHINA.</p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF HONG KONG: THE CONTENTS OF THIS DOCUMENT HAVE NOT BEEN REVIEWED OR APPROVED BY ANY REGULATORY AUTHORITY IN HONG KONG. YOU ARE ADVISED TO EXERCISE CAUTION IN RELATION TO TOKENS DESCRIBED HEREIN. IF YOU ARE IN ANY DOUBT ABOUT ANY OF THE CONTENTS OF THIS DOCUMENT, YOU SHOULD OBTAIN INDEPENDENT PROFESSIONAL ADVICE. THIS DOCUMENT DOES NOT CONSTITUTE AN OFFER OR INVITATION TO THE PUBLIC IN HONG KONG TO ACQUIRE THE TOKENS DESCRIBED HEREIN. ACCORDINGLY, UNLESS PERMITTED BY THE LAWS OF HONG KONG, NO PERSON MAY ISSUE OR HAVE IN ITS POSSESSION FOR THE PURPOSES OF ISSUE, THIS DOCUMENT RELATING TO THE TOKENS BEING DESCRIBED, WHETHER IN HONG KONG OR ELSEWHERE, WHICH IS DIRECTED AT, OR THE CONTENTS OF WHICH ARE LIKELY TO BE ACCESSED OR READ BY, THE PUBLIC IN HONG KONG OTHER THAN IN CIRCUMSTANCES WHICH DO NOT RESULT IN THIS DOCUMENT CONSTITUTING A “PROSPECTUS” AS DEFINED IN THE COMPANIES (WINDING UP AND MISCELLANEOUS PROVISIONS) ORDINANCE OF HONG KONG (CAP. 32 OF THE LAWS OF HONG KONG) (THE “C(WUMP)O”) OR WHICH DO NOT CONSTITUTE AN OFFER OR AN INVITATION TO THE PUBLIC FOR THE PURPOSES OF THE SECURITIES AND FUTURES ORDINANCE (CAP. 571 OF THE LAWS OF HONG KONG) OR THE C(WUMP)O. AN OFFER OF THE TOKENS IS PERSONAL TO THE PERSON TO WHOM THIS DOCUMENT HAS BEEN DELIVERED, AND THE TOKENS WILL ONLY BE ACCEPTED BY SUCH PERSON. NO PERSON TO WHOM A COPY OF THIS DOCUMENT IS ISSUED MAY ISSUE, CIRCULATE OR DISTRIBUTE THIS DOCUMENT IN HONG KONG OR MAKE OR GIVE A COPY OF THIS DOCUMENT TO ANY OTHER PERSON.
                </p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF SOUTH KOREA: THIS AGREEMENT IS NOT, AND UNDER NO CIRCUMSTANCES IS TO BE CONSTRUED AS, AN OFFERING OF SECURITIES IN SOUTH KOREA UNDER THE FINANCIAL INVESTMENT SERVICES AND CAPITAL MARKETS ACT OF SOUTH KOREA (THE “FISCMA”). FOR THE PURPOSE OF THIS NOTICE, THE EXPRESSION “OFFERING” IN RELATION TO ANY SECURITIES UNDER FISCMA MEANS THE INVITATION OF SUBSCRIPTION FOR NEWLY ISSUED SECURITIES TO MORE THAN 50 RETAIL INVESTORS. THE TOKENS DESCRIBED HEREIN HAVE NOT BEEN REGISTERED AS SECURITIES UNDER THE FISCMA, AND THIS SECURITY MAY NOT BE OFFERED, SOLD, TRANSFERRED, PLEDGED OR HYPOTHECATED, DIRECTLY OR INDIRECTLY, OR OFFERED OR SOLD TO ANY PERSON FOR RE-OFFERING OR RE-SALE, DIRECTLY OR INDIRECTLY, IN SOUTH KOREA OR TO ANY RESIDENT OF SOUTH KOREA.
                </p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF CUBA, IRAN, NORTH KOREA, SYRIA, AND THE CRIMEA REGION: THIS IS NOT BEING OFFERED OR DISTRIBUTED TO ANY RESIDENT OF OR ANY PERSON LOCATED OR DOMICILED IN CUBA, IRAN, NORTH KOREA, SYRIA, THE CRIMEA REGION OR ANY OTHER COUNTRY OR TERRITORY THAT IS THE SUBJECT OF COUNTRY-WIDE OR TERRITORY-WIDE SANCTIONS.
                </p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF THE UNITED STATES: THE OFFER AND SALE OF THIS SECURITY HAS NOT BEEN REGISTERED UNDER THE U.S. SECURITIES ACT OF 1933, AS AMENDED (THE “U.S. SECURITIES ACT”), OR UNDER THE SECURITIES LAWS OF ANY U.S. STATES. THIS SECURITY MAY NOT BE OFFERED, SOLD OR OTHERWISE TRANSFERRED, PLEDGED OR HYPOTHECATED IN THE UNITED STATES OR TO U.S. PERSONS ANYWHERE EXCEPT AS PERMITTED UNDER THE U.S. SECURITIES ACT AND APPLICABLE U.S. STATE SECURITIES LAWS PURSUANT TO AN EFFECTIVE REGISTRATION STATEMENT OR AN EXEMPTION THEREFROM. THIS AGREEMENT HAS NOT BEEN APPROVED FOR TRADING BY THE U.S. COMMODITY FUTURES TRADING COMMISSION (THE “CFTC”) UNDER THE COMMODITY EXCHANGE ACT OF 1936, AS AMENDED (THE “CEA”).</p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF NEW YORK STATE: THIS SECURITY IS NOT BEING OFFERED OR DISTRIBUTED TO ANY RESIDENT OF, OR ANY PERSON LOCATED OR DOMICILED IN, THE STATE OF NEW YORK OR ANY ENTITY, INCLUDING, WITHOUT LIMITATION, ANY CORPORATION OR PARTNERSHIP CREATED OR ORGANIZED IN OR UNDER THE LAWS OF THE STATE OF NEW YORK (“NEW YORK PERSON”). THE ISSUER IS NOT SOLICITING PURCHASES BY NEW YORK PERSONS IN ANY WAY.
                </p>
            </div>
            <div>
                <p>
                    OTHER COUNTRIES AND TERRITORIES: NUMEROUS OTHER COUNTRIES AND TERRITORIES MAY HAVE RESTRICTIONS AGAINST THE PURCHASE AND SALE OF THE TOKENS DESCRIBED HEREIN. PLEASE CONSULT YOUR OWN COUNSEL IN THAT REGARD.</p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF CANADA: UNLESS PERMITTED UNDER SECURITIES LEGISLATION, THE HOLDER OF THIS SECURITY MUST NOT TRADE THE SECURITY BEFORE THE DATE THAT THE ISSUER BECOMES A REPORTING ISSUER IN ANY PROVINCE OR TERRITORY.
                </p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF THE EUROPEAN ECONOMIC AREA (THE “EEA”): IN RELATION TO EACH MEMBER STATE OF THE EEA, NO OFFER OF SECURITIES MAY BE MADE TO THE PUBLIC IN THAT MEMBER STATE EXCEPT: (A) TO ANY LEGAL ENTITY WHICH IS A QUALIFIED INVESTOR AS DEFINED IN THE PROSPECTUS DIRECTIVE; (B) TO FEWER THAN 150 NATURAL OR LEGAL PERSONS (OTHER THAN QUALIFIED INVESTORS AS DEFINED IN THE PROSPECTUS DIRECTIVE) AS PERMITTED UNDER THE PROSPECTUS DIRECTIVE; OR (C) UNDER ANY OTHER CIRCUMSTANCES FALLING WITHIN ARTICLE 3(2) OF THE PROSPECTUS DIRECTIVE, PROVIDED THAT NO SUCH OFFER OF SECURITIES WILL REQUIRE THE ISSUER TO PUBLISH A PROSPECTUS PURSUANT TO ARTICLE 3 OF THE PROSPECTUS DIRECTIVE, OR SUPPLEMENT A PROSPECTUS PURSUANT TO ARTICLE 16 OF THE PROSPECTUS DIRECTIVE.</p>
            </div>
            <div>
                <p>
                    THIS SECURITY IS NOT INTENDED TO BE OFFERED, SOLD OR OTHERWISE MADE AVAILABLE TO AND SHOULD NOT BE OFFERED, SOLD OR OTHERWISE MADE AVAILABLE TO ANY RETAIL INVESTOR IN THE EEA. FOR THESE PURPOSES, A RETAIL INVESTOR MEANS A PERSON WHO IS ONE (OR MORE) OF: (I) A RETAIL CLIENT AS DEFINED IN POINT (11) OF ARTICLE 4(1) OF DIRECTIVE 2014/65/EU (“MIFID II”); OR (II) A CUSTOMER WITHIN THE MEANING OF DIRECTIVE 2002/92/EC, WHERE THAT CUSTOMER WOULD NOT QUALIFY AS A PROFESSIONAL CLIENT AS DEFINED IN POINT (10) OF ARTICLE 4(1) OF MIFID II; OR (III) NOT A QUALIFIED INVESTOR AS DEFINED IN THE PROSPECTUS DIRECTIVE. CONSEQUENTLY, NO KEY INFORMATION DOCUMENT REQUIRED BY REGULATION (EU) NO 1286/2014 (THE “PRIIPS REGULATION”) FOR OFFERING OR SELLING THIS SECURITY OR OTHERWISE MAKING IT AVAILABLE TO RETAIL INVESTORS IN THE EEA HAS BEEN PREPARED AND THEREFORE OFFERING OR SELLING THIS SECURITY OR OTHERWISE MAKING IT AVAILABLE TO ANY RETAIL INVESTOR IN THE EEA MAY BE UNLAWFUL UNDER THE PRIIPS REGULATION. IT IS A CONDITION OF YOU RECEIVING AND RETAINING THIS DOCUMENT THAT YOU WARRANT THAT YOU ARE A QUALIFIED INVESTOR.
                </p>
            </div>
            <div>
                <p>
                    FOR THE PURPOSES OF THIS NOTICE, THE EXPRESSION AN “OFFER TO THE PUBLIC” IN RELATION TO ANY SECURITIES IN ANY MEMBER STATE MEANS THE COMMUNICATION IN ANY FORM AND BY ANY MEANS OF SUFFICIENT INFORMATION ON THE TERMS OF THE OFFER AND THE SECURITY BEING OFFERED SO AS TO ENABLE AN INVESTOR TO DECIDE TO PURCHASE THE SECURITY, AS THE SAME MAY BE VARIED IN THAT MEMBER STATE BY ANY MEASURE IMPLEMENTING THE PROSPECTUS DIRECTIVE IN THAT MEMBER STATE. THE EXPRESSION “PROSPECTUS DIRECTIVE” MEANS DIRECTIVE 2003/71/EC (AS AMENDED, INCLUDING BY DIRECTIVE 2010/73/EU), AND INCLUDES ANY RELEVANT IMPLEMENTING MEASURE IN ANY MEMBER STATE.</p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF THE UNITED KINGDOM: IN THE UNITED KINGDOM, THIS DOCUMENT IS BEING DISTRIBUTED ONLY TO, AND IS DIRECTED ONLY AT (AND ANY INVESTMENT ACTIVITY TO WHICH IT RELATES WILL BE ENGAGED ONLY WITH) QUALIFIED INVESTORS (WITHIN THE MEANING OF ARTICLE 2(1)(E) OF THE PROSPECTUS DIRECTIVE), AND WHO HAVE PROFESSIONAL EXPERIENCE IN MATTERS RELATING TO INVESTMENTS FALLING WITHIN ARTICLE 19(5) OF THE FINANCIAL SERVICES AND MARKETS ACT 2000 (FINANCIAL PROMOTION) ORDER 2005, AS AMENDED (THE “FPO”) OR WHO FALL WITHIN ARTICLE 49(2) OF THE FPO (ALL SUCH PERSONS BEING REFERRED TO AS “RELEVANT PERSONS”). THIS DOCUMENT HAS NOT BEEN APPROVED BY AN AUTHORISED PERSON. ANY INVESTMENT TO WHICH THIS DOCUMENT RELATES IS AVAILABLE ONLY TO (AND ANY INVESTMENT ACTIVITY TO WHICH IT RELATES WILL BE ENGAGED ONLY WITH) RELEVANT PERSONS. THIS DOCUMENT IS DIRECTED ONLY AT RELEVANT PERSONS AND PERSONS WHO ARE NOT RELEVANT PERSONS SHOULD NOT TAKE ANY ACTION BASED UPON THIS DOCUMENT AND SHOULD NOT RELY ON IT. IT IS A CONDITION OF YOU RECEIVING AND RETAINING THIS DOCUMENT THAT YOU WARRANT THAT YOU ARE A RELEVANT PERSON.
                </p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF FRANCE: THIS DOCUMENT HAS NOT BEEN PREPARED, AND IS NOT DISTRIBUTED, IN THE CONTEXT OF A PUBLIC OFFERING OF FINANCIAL SECURITIES IN FRANCE WITHIN THE MEANING OF ARTICLE L. 411-1 OF THE FRENCH CODE MONÉTAIRE ET FINANCIER. CONSEQUENTLY, NO FINANCIAL SECURITIES HAVE BEEN OFFERED OR SOLD OR WILL BE OFFERED OR SOLD, DIRECTLY OR INDIRECTLY, TO THE PUBLIC IN FRANCE, AND ANY OFFERING MATERIAL MAY NOT BE, AND WILL NOT BE, DISTRIBUTED OR CAUSED TO BE DISTRIBUTED TO THE PUBLIC IN FRANCE OR USED IN CONNECTION WITH ANY OFFER TO THE PUBLIC IN FRANCE.</p>
            </div>
            <div>
                <p>
                    OFFERS, SALES AND DISTRIBUTIONS OF SECURITIES WILL BE MADE ONLY TO QUALIFIED INVESTORS (INVESTISSEURS QUALIFIÉS) ACTING FOR THEIR OWN ACCOUNT, ALL AS DEFINED IN, AND IN ACCORDANCE WITH, ARTICLES L. 411-2, D. 411-1, D. 744-1 D. 754-1, AND D. 764-1 OF THE FRENCH CODE MONÉTAIRE ET FINANCIER AND APPLICABLE REGULATIONS THEREUNDER.
                </p>
            </div>
            <div>
                <p>
                    PROSPECTIVE INVESTORS ARE INFORMED THAT (I) NO PROSPECTUS HAS BEEN AND WILL BE SUBMITTED TO THE CLEARANCE OF THE FRENCH FINANCIAL MARKET AUTHORITY (“AMF”), (II) IN COMPLIANCE WITH ARTICLES L. 411-1, D. 411-1, D. 744-1, D. 754-1, AND D. 764-1 OF THE FRENCH CODE MONÉTAIRE ET FINANCIER, ANY QUALIFIED INVESTOR SHOULD BE ACTING FOR ITS OWN ACCOUNT, AND (III) THE DIRECT OR INDIRECT DISTRIBUTION OR SALE TO THE PUBLIC OF SECURITIES MAY ONLY BE MADE IN COMPLIANCE WITH ARTICLES L. 411-1, L. 411-2, L. 412-1, AND L. 621-8 THROUGH L. 621-8-3 OF THE FRENCH CODE MONÉTAIRE ET FINANCIER.</p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF GERMANY: IN THE FEDERAL REPUBLIC OF GERMANY THIS DOCUMENT IS DISTRIBUTED ONLY TO, AND IS DIRECTED ONLY AT, QUALIFIED INVESTORS WITHIN THE MEANING OF THE PROSPECTUS DIRECTIVE, THAT PROFESSIONALLY OR COMMERCIALLY PURCHASE OR SELL SECURITIES OR INVESTMENT PRODUCTS (VERMÖGENSANLAGEN) WITHIN THE MEANING OF THE GERMAN INVESTMENT PRODUCT ACT (VERMÖGENSANLAGENGESETZ) FOR THEIR OWN ACCOUNT OR FOR THE ACCOUNT OF OTHERS. NO SECURITIES PROSPECTUS (WERTPAPIERPROSPEKT) OR INVESTMENT PRODUCT PROSPECTUS (VERMÖGENSANLAGENVERKAUFSPROSPEKT) HAS BEEN OR WILL BE FILED WITH THE GERMAN FEDERAL FINANCIAL SUPERVISORY AUTHORITY (BAFIN) OR OTHERWISE PUBLISHED IN THE FEDERAL REPUBLIC OF GERMANY. NO PUBLIC OFFER OR DISTRIBUTION OF COPIES OF ANY DOCUMENT RELATING TO THE NETWORK OR THE TOKENS INCLUDING THIS DOCUMENT, WILL BE MADE IN THE FEDERAL REPUBLIC OF GERMANY EXCEPT WHERE AN EXPRESS EXEMPTION FROM COMPLIANCE WITH THE PUBLIC OFFER RESTRICTIONS UNDER THE GERMAN SECURITIES PROSPECTUS ACT AND THE INVESTMENT PRODUCT ACT APPLIES.
                </p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF SWITZERLAND: THIS DOCUMENT (AND ANY OTHER OFFERING OR MARKETING MATERIAL WITH RESPECT TO THE INVESTMENT ACTIVITY TO WHICH THIS DOCUMENT RELATES) MAY BE DISTRIBUTED OR MADE AVAILABLE IN, INTO OR FROM SWITZERLAND ONLY TO QUALIFIED INVESTORS WITHIN THE MEANING OF THE SWISS COLLECTIVE INVESTMENT SCHEMES ACT (“CISA”), ITS IMPLEMENTING ORDINANCE AND REGULATORY GUIDANCE (EACH SUCH PERSON A “QUALIFIED INVESTOR”). THIS DOCUMENT (NOR ANY OTHER OFFERING OR MARKETING MATERIAL WITH RESPECT TO THE INVESTMENT ACTIVITY TO WHICH THIS DOCUMENT RELATES) HAS NOT BEEN AND WILL NOT BE FILED WITH, OR APPROVED BY, ANY SWISS REGULATORY AUTHORITY. THIS DOCUMENT DOES NOT CONSTITUTE AN OFFER TO SUBSCRIBE FOR, BUY OR OTHERWISE ACQUIRE ANY TOKENS AND IT DOES NOT CONSTITUTE A PROSPECTUS PURSUANT TO THE CISA, THE SWISS CODE OF OBLIGATIONS OR THE LISTING RULES OF ANY TRADING VENUE IN SWITZERLAND. ANY INVESTMENT TO WHICH THIS DOCUMENT RELATES IS AVAILABLE ONLY TO (AND ANY INVESTMENT ACTIVITY TO WHICH IT RELATES WILL BE ENGAGED ONLY WITH) QUALIFIED INVESTORS.</p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF AUSTRALIA: THIS DOCUMENT IS NOT A PRODUCT DISCLOSURE STATEMENT OR DISCLOSURE DOCUMENT FOR THE PURPOSES OF THE AUSTRALIAN CORPORATIONS ACT 2001 (CTH) (“CORPORATIONS ACT”) AND IS NOT REQUIRED TO BE LODGED WITH THE AUSTRALIAN SECURITIES AND INVESTMENTS COMMISSION (“ASIC”). THIS OFFER IS MADE IN CIRCUMSTANCES THAT WOULD NOT REQUIRE DISCLOSURE UNDER CHAPTER 6D OR CHAPTER 7 OF THE CORPORATIONS ACT. THIS DOCUMENT IS NOT REQUIRED TO, AND DOES NOT, CONTAIN ALL THE INFORMATION WHICH WOULD BE REQUIRED IN A DISCLOSURE DOCUMENT OR PRODUCT DISCLOSURE STATEMENT, OR ALL THE INFORMATION THAT A PROSPECTIVE INVESTOR MAY DESIRE OR SHOULD OBTAIN IN ORDER TO MAKE AN INFORMED INVESTMENT DECISION. BY ACCEPTING RECEIPT OF THIS DOCUMENT, YOU REPRESENT AND WARRANT THAT YOU ARE A “SOPHISTICATED INVESTOR” AS DEFINED UNDER SECTION 708(8) OF THE CORPORATIONS ACT OR A “PROFESSIONAL INVESTOR” UNDER SECTION 708(11) OF THE CORPORATIONS ACT AND A “WHOLESALE CLIENT” UNDER SECTION 761G OF THE CORPORATIONS ACT. THE ISSUER OF THIS DOCUMENT IS NOT REGISTERED AS A MANAGED INVESTMENT SCHEME UNDER THE CORPORATIONS ACT. ANY PERSON TO WHOM THIS DOCUMENT IS ISSUED MUST NOT, WITHIN 12 MONTHS AFTER SUCH ISSUE, OFFER, TRANSFER OR ASSIGN THIS DOCUMENT TO PERSONS IN AUSTRALIA EXCEPT IN CIRCUMSTANCES WHERE DISCLOSURE TO SUCH PERSONS IS NOT REQUIRED UNDER THE CORPORATIONS ACT.
                </p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF ISRAEL: THIS DOCUMENT DOES NOT CONSTITUTE A PROSPECTUS UNDER THE ISRAELI SECURITIES LAW OF 1968 (THE “ISRAELI SECURITIES LAW”), AND HAS NOT BEEN REVIEWED, FILED WITH OR APPROVED BY THE ISRAELI SECURITIES AUTHORITY OR ANY OTHER ISRAELI GOVERNMENT OR REGULATORY BODY. THIS DOCUMENT, ANY INVESTMENT ACTIVITY TO WHICH IT RELATES AND ANY OFFERING OF THE TOKENS IN ISRAEL IS AND WILL BE EXCLUSIVELY DISTRIBUTED OR MADE TO, AND DIRECTED AT, QUALIFIED INVESTORS, AS DEFINED IN SCHEDULE 1 OF THE ISRAELI SECURITIES LAW. PERSONS WHO ARE NOT QUALIFIED INVESTORS SHOULD NOT TAKE ANY ACTION BASED UPON THIS DOCUMENT AND SHOULD NOT RELY ON IT.</p>
            </div>
            <div>
                <p>
                    NOTICE TO RESIDENTS OF RUSSIA:INFORMATION CONTAINED HEREIN IS NOT AN OFFER, OR AN INVITATION TO MAKE OFFERS, TO SELL, PURCHASE, EXCHANGE OR OTHERWISE TRANSFER SECURITIES OR FOREIGN FINANCIAL INSTRUMENTS IN THE RUSSIAN FEDERATION TO OR FOR THE BENEFIT OF ANY RUSSIAN PERSON OR ENTITY, EXCEPT “QUALIFIED INVESTORS” (AS DEFINED UNDER RUSSIAN SECURITIES LAWS) TO THE EXTENT PERMITTED UNDER RUSSIAN SECURITIES LAWS. THIS DOCUMENT IS NOT AN ADVERTISEMENT IN CONNECTION WITH THE “PLACEMENT” OR “PUBLIC CIRCULATION” (AS BOTH TERMS ARE DEFINED UNDER RUSSIAN SECURITIES LAW) OF ANY SECURITIES, AND ANY FINANCIAL INSTRUMENTS DESCRIBED HEREIN ARE NOT INTENDED FOR “PLACEMENT” OR “PUBLIC CIRCULATION” IN THE RUSSIAN FEDERATION, IN EACH CASE UNLESS OTHERWISE PERMITTED UNDER RUSSIAN SECURITIES LAWS. NEITHER ANY FINANCIAL INSTRUMENTS DESCRIBED HEREIN NOR A PROSPECTUS RELATING TO SUCH FINANCIAL INSTRUMENTS HAS BEEN OR WILL BE REGISTERED WITH THE CENTRAL BANK OF THE RUSSIAN FEDERATION.
                </p>
            </div>
        </div>
    </div>
</template>
<script>
export default {
    name: 'disclaimers',
    data() {
        return {

        }
    },
    methods: {

    },
    components: {


    }
}
</script>
<style>

</style>
